import type { PlanVersion, TripDay } from './types';

export const baseDays: TripDay[] = [
  {
    id: 'day-1',
    date: '10月2日',
    weekday: '周五',
    title: '园林与旧城初见',
    weather: '24° 晴',
    walking: '6.8 km',
    items: [
      {
        id: 'train-arrival',
        time: '09:38',
        title: '抵达苏州站',
        category: '交通',
        duration: '35 分钟',
        cost: 12,
        travel: '地铁 4 号线 · 18 分钟',
        reason: '先到酒店寄存行李，减少全天负重。',
        source: '苏州轨道交通',
        freshness: '演示数据',
        status: 'booked',
        coordinates: [31.33087, 120.60629],
      },
      {
        id: 'museum',
        time: '11:00',
        title: '苏州博物馆',
        category: '人文',
        duration: '1 小时 40 分',
        cost: 0,
        travel: '步行 9 分钟',
        reason: '室内参观作为抵达后的轻松开场，建筑本身也值得看。',
        source: '官方预约页',
        freshness: '演示数据',
        locked: true,
        status: 'booked',
        coordinates: [31.32466, 120.6272],
      },
      {
        id: 'humble-garden',
        time: '14:10',
        title: '拙政园',
        category: '园林',
        duration: '2 小时',
        cost: 80,
        travel: '步行 6 分钟',
        reason: '用户必去；午后光线适合看水景与园林层次。',
        source: '景区官网',
        freshness: '演示数据',
        locked: true,
        status: 'planned',
        coordinates: [31.32693, 120.62617],
      },
      {
        id: 'pingjiang',
        time: '17:05',
        title: '平江路慢行',
        category: '街区',
        duration: '1 小时 30 分',
        cost: 60,
        travel: '步行 12 分钟',
        reason: '傍晚沿河慢走，途中安排茶歇，避免连续赶景点。',
        source: '两篇导入攻略',
        freshness: '演示数据',
        locked: true,
        status: 'planned',
        coordinates: [31.3141, 120.63155],
      },
    ],
  },
  {
    id: 'day-2',
    date: '10月3日',
    weekday: '周六',
    title: '城西园林与山塘夜色',
    weather: '21° 有雨',
    walking: '9.4 km',
    items: [
      {
        id: 'tiger-hill',
        time: '09:00',
        title: '虎丘',
        category: '古迹',
        duration: '2 小时 20 分',
        cost: 70,
        travel: '打车 24 分钟',
        reason: '上午人少，但园区坡路较多，需要预留休息。',
        source: '景区官网',
        freshness: '演示数据',
        status: 'planned',
        coordinates: [31.338, 120.5754],
      },
      {
        id: 'songhelou',
        time: '12:10',
        title: '松鹤楼午餐',
        category: '餐饮',
        duration: '1 小时 10 分',
        cost: 240,
        travel: '打车 18 分钟',
        reason: '有清淡菜可选，适合与长辈同行。',
        source: '用户收藏',
        freshness: '演示数据',
        status: 'planned',
        coordinates: [31.3147, 120.6218],
      },
      {
        id: 'lingering-garden',
        time: '14:20',
        title: '留园',
        category: '园林',
        duration: '2 小时',
        cost: 55,
        travel: '步行 18 分钟',
        reason: '与上午的虎丘形成园林与古迹组合。',
        source: '景区官网',
        freshness: '缓存',
        status: 'planned',
        coordinates: [31.3174, 120.5918],
      },
      {
        id: 'shantang',
        time: '17:30',
        title: '山塘街夜游',
        category: '街区',
        duration: '1 小时 40 分',
        cost: 80,
        travel: '步行 22 分钟',
        reason: '夜景有辨识度，但雨天石板路可能湿滑。',
        source: '三篇导入攻略',
        freshness: '演示数据',
        status: 'planned',
        coordinates: [31.3211, 120.6052],
      },
    ],
  },
  {
    id: 'day-3',
    date: '10月4日',
    weekday: '周日',
    title: '湖畔散步与从容返程',
    weather: '23° 多云',
    walking: '4.6 km',
    items: [
      {
        id: 'jinji-lake',
        time: '09:30',
        title: '金鸡湖步道',
        category: '自然',
        duration: '1 小时 20 分',
        cost: 0,
        travel: '地铁 1 号线 · 28 分钟',
        reason: '最后一天降低密度，保留湖边休息时间。',
        source: '苏州文旅',
        freshness: '演示数据',
        status: 'planned',
        coordinates: [31.3157, 120.7005],
      },
      {
        id: 'suzhou-center',
        time: '11:30',
        title: '苏州中心午餐',
        category: '餐饮',
        duration: '1 小时 30 分',
        cost: 180,
        travel: '步行 10 分钟',
        reason: '室内选择多，返程前方便补给。',
        source: '地图检索',
        freshness: '演示数据',
        status: 'planned',
        coordinates: [31.3173, 120.6744],
      },
      {
        id: 'return-train',
        time: '15:18',
        title: '苏州站返程',
        category: '交通',
        duration: '38 分钟',
        cost: 78,
        travel: '地铁 1→4 号线 · 34 分钟',
        reason: '提前 55 分钟到站，给长辈留出从容进站时间。',
        source: '用户录入车票',
        freshness: '演示数据',
        locked: true,
        status: 'booked',
        coordinates: [31.33087, 120.60629],
      },
    ],
  },
];

export const rainPlanItems = [
  {
    ...baseDays[1].items[0],
    id: 'silk-museum',
    time: '09:40',
    title: '苏州丝绸博物馆',
    category: '室内',
    duration: '1 小时 30 分',
    cost: 0,
    travel: '地铁 4 号线 · 16 分钟',
    reason: '替代坡路较多的虎丘，雨天室内且步行量更低。',
    source: '官方页面',
    coordinates: [31.32864, 120.61572] as [number, number],
  },
  {
    ...baseDays[1].items[1],
    time: '11:50',
    travel: '打车 12 分钟',
  },
  {
    ...baseDays[1].items[2],
    time: '13:40',
    duration: '1 小时 40 分',
    travel: '打车 9 分钟',
  },
  {
    ...baseDays[1].items[3],
    id: 'pintan-teahouse',
    time: '16:10',
    title: '评弹茶馆',
    category: '室内体验',
    duration: '1 小时 20 分',
    cost: 120,
    travel: '打车 13 分钟',
    reason: '用室内评弹替代湿滑夜游，保留苏州地方体验。',
    source: '导入攻略 + 地图检索',
    coordinates: [31.3137, 120.6229] as [number, number],
  },
];

export const initialVersions: PlanVersion[] = [
  {
    id: 'v1',
    title: 'V1 · 初始规划',
    time: '今天 10:24',
    note: '根据同行人、预算和必去地点生成',
    active: true,
  },
];
