source "https://rubygems.org"

# GitHub Pages Jekyll gem
gem "github-pages", "~> 232", group: :jekyll_plugins

# Jekyll plugins
gem "jekyll-include-cache", group: :jekyll_plugins
gem "jekyll-feed", group: :jekyll_plugins
gem "jekyll-sitemap", group: :jekyll_plugins

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# Fix Ruby 3.x compatibility
gem "webrick", "~> 1.7" 